language: node_js
node_js: stable
cache:
  directories:
    - node_modules

before_install:
  - wget https://github.com/jgm/pandoc/releases/download/2.9/pandoc-2.9-1-amd64.deb
  - sudo dpkg -i ./pandoc-2.9-1-amd64.deb
  
install:
  - npm install -g hexo-cli
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "lizhengyi"
  - git config user.email "lizhengyi@pku.edu.cn"
  - git checkout -b travis
  - git add .
  - git commit -m "Update blog content by Travis CI"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/li-positive-one/blog.git" travis:travis

branches:
  only:
    - docs
