language: node_js
node_js: stable
cache:
  directories:
    - node_modules

install:
  - sudo apt-get install -y pandoc
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "lizhengyi"
  - git config user.email "lizhengyi@pku.edu.cn"
  - git add .
  - git commit -m "Update blog content by Travis CI"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - docs