name: Hexo

on:
  push:
    branches:
      - docs
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      run: |
        git submodule update --init --recursive
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install pandoc
      run: |
        wget https://github.com/jgm/pandoc/releases/download/2.9/pandoc-2.9-1-amd64.deb
        sudo dpkg -i ./pandoc-2.9-1-amd64.deb
    - name: npm install, build, and test
      run: |
        npm install -g hexo-cli
        npm install 
      env:
        CI: true
    - name: building
      run: |
        hexo g
    - name: set ssh
      env:
        ACTION_DEPLOY_KEY: ${{ secrets.GH_KEY }}
      run: |
        # set up private key for deploy
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: deploying
      run: |
        cd ./public
        git init
        git config user.name "lizhengyi"
        git config user.email "lizhengyi@pku.edu.cn"
        git add .
        git commit -m "Update blog content by Github Actions"
        git push --force --quiet git@github.com:li-positive-one/li-positive-one.github.io.git master:master
